version: '3.8'

services:
  uppbeatlibraryapi:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOCKER_ENVIRONMENT=true
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=uppbeatapi;Username=uppbeatapp;Password=your_strong_password;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - uppbeatlib-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: uppbeatapi
      POSTGRES_USER: uppbeatapp
      POSTGRES_PASSWORD: your_strong_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uppbeatapp -d uppbeatapi"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - uppbeatlib-network

networks:
  uppbeatlib-network:
    driver: bridge

volumes:
  postgres_data:
